---
# 关于通过网络安装CentOS的详细配置参考文档:
# https://docs.centos.org/en-US/centos/install-guide/pxe-server/#sect-network-boot-setup-uefi
# deploy-pxeserver.yml
- hosts: localhost
  transport: local
  host_key_checking: False
  gather_facts: yes
  become: yes
  become_method: su
  vars:
      # pxe主机地址
      ip: "{{ ansible_facts.all_ipv4_addresses.1 }}"
      # 安装源目录
      install_resource_path: "/media/CentOS"
      # TFTP服务目录
      tftpd_root_path: "/var/lib/tftpboot"
      # ks文件路径,以TFTP为根
      ksfile_pathname: "/kickstart/ks.cfg"
      # grub.cfg文件路径,以TFTP为根
      grub_cfg_file_pathname: "/EFI/BOOT/grub.cfg"
  tasks:
  - name: INSTALL nfs,tftp,dhcp服务
    yum:
        name: nfs-utils,tftp-server,dhcp
        state: present
        enablerepo: 'c7-media'
        disablerepo: 'base,extras,updates'
  - name: CONFIG nfs option
    lineinfile:
        backup: no
        create: yes
        path: /etc/exports
        state: present
        # 注意pxe server ip包含在此网络中
        line: '{{ item.nfs_export }}'
    loop:
        - { nfs_export: "{{ install_resource_path }} 192.168.0.0/16(ro)" }
        - { nfs_export: "{{ tftp_root_path }} 192.168.0.0/16(rw)" }
    tags: nfs
    notify:
      - RESTART nfs service

  - name: CONFIG tftp option
    command:
        argv:
        - /usr/bin/cp
        - '-fr'
        - '{{ item.sf }}'
        - {{ tftp_root_path }}/
        creates: '{{ item.df }}'
    loop: 
        - { sf: {{ install_resource_path }}/EFI, df: {{ tftp_root_path }}/EFI }
        - { sf: {{ install_resource_path }}/images, df: {{ tftp_root_path }}/images }
    tags: tftp

#  - name: CONFIG tftp option
#    command:
#        argv:
#        - /usr/bin/cp
#        - '{{ item.sf }}'
#        - {{ tftp_root_path }}/
#        creates: '{{ item.df }}'
#    loop: 
#        - { sf: {{ install_resource_path }}/EFI/BOOT/grubaa64.efi, df: {{ tftp_root_path }}/grubaa64.efi }
#        - { sf: {{ install_resource_path }}/EFI/BOOT/grub.cfg, df: {{ tftp_root_path }}/grub.cfg }
#        - { sf: {{ install_resource_path }}/images/pxeboot/vmlinuz, df: {{ tftp_root_path }}/vmlinuz }
#        - { sf: {{ install_resource_path }}/images/pxeboot/initrd.img, df: {{ tftp_root_path }}/initrd.img }

  - name: CONFIG uefi boot option while installing os
    replace:
        backup: no
        path: {{ tftp_root_path }}/{{ grub_cfg_file_pathname }}
        regexp: '{{ item.mat }}'
        replace: '{{ item.rep }}'
    loop:
        - { mat: '[ ]+inst\.(stage2|ks)=[^ ]+[ ]+', rep: ' inst.ks=nfs:{{ ip }}:{{ tftp_root_path }}/{{ ksfile_pathname }} ' }
        - { mat: '^set default="\d+"$', rep: 'set default="0"' }
        - { mat: '^set timeout=\d+$', rep: 'set timeout=6' }
    tags: grub

  - name: CONFIG dhcp server
    blockinfile:
        path: /etc/dhcp/dhcpd.conf
        # 注意dhcp server ip和地址范围
        block: |
            default-lease-time 600;
            max-lease-time 7200;
            # 21掩码8C地址128-135
            subnet 192.168.128.0 netmask 255.255.248.0 { 
                range dynamic-bootp 192.168.129.0 192.168.130.255;
                # 以TFTP为根
                filename "grubaa64.efi";
                next-server {{ ip }};
            }
    notify:
      - RESTART dhcp service
    tags: dhcp

  - name: START nfs,tftp,dhcp server
    systemd:
        name: '{{ item.service_name }}'
        state: started
        enabled: no
    loop:
        - { service_name: nfs }
        - { service_name: tftp.socket }
        - { service_name: dhcpd }

  - name: show ip
    debug: msg={{ ip }}

  handlers:
  - name: RESTART nfs service
    systemd:
        name: nfs
        daemon_reload: yes
        state: restarted
  - name: RESTART dhcp service
    systemd:
        name: dhcpd
        daemon_reload: yes
        state: restarted
...
